
name: notification_system
description: "A complete cross-platform notification system for Flutter apps with Firebase Cloud Messaging, BLoC pattern, and device management."
version: 1.0.0
homepage: https://github.com/yourrepo/notification_system
repository: https://github.com/yourrepo/notification_system
issue_tracker: https://github.com/yourrepo/notification_system/issues
documentation: https://github.com/yourrepo/notification_system#readme

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Dependencies
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  
  # Local Notifications
  flutter_local_notifications: ^17.0.0
  
  # State Management (BLoC)
  flutter_bloc: ^8.1.4
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # UI & UX
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  
  # Utilities
  permission_handler: ^11.2.0
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  intl: ^0.19.0
  uuid: ^4.3.3
  
  # Platform specific
  platform: ^3.1.4
  
  # Functional Programming
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
